# Where things are
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir: ./_data

# Handling Reading
safe: false
include: [".htaccess"]
exclude: [
  "bower.json",
  "package.json",
  "tslint.json",
  "assets"
]
keep_files:   [".git"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
#whitelist: []
gems: [jekyll-paginate]

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# GitHub
github:
  repository_url: "https://github.com/OAWest/western.oa-bsa.org"

# Sass
sass:
  sass_dir: _sass

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "/"
url: "http://western.oa-bsa.org"

# Outputting
permalink: date
paginate: 10
paginate_path: /page:num
timezone: null
reading_time: true
words_per_minute: 200
quiet:    false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style


include: ['_pages']

# Site Information
title: Western Region, Order of the Arrow, BSA
description: >
  Official website of the Western Region, Order of the Arrow, Boy Scouts of America
email:
  webmaster: webmaster@western.oa-bsa.org
social:
  facebook: https://www.facebook.com/oawest
  google_plus: https://plus.google.com/111522187744944747027#111522187744944747027
  instagram: https://www.instagram.com/oawest
  twitter: https://twitter.com/oawest